version : '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

  
  ts_app:
    build:
      network: host
      context: ./
      dockerfile : Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres

    ports:
      - 3000:3000

    depends_on:
      - postgres
    command: sh -c "sleep 5 && npx prisma migrate deploy && node dist/index.js"